# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='install_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='ipaddr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='install_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='ipaddr',
            field=models.TextField(blank=True),
        ),
    ]
