# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0002_auto_20170211_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bac.Action'),
            preserve_default=False,
        ),
    ]
