# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0003_relay_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('card_id', models.TextField()),
                ('card_id_type', models.IntegerField()),
                ('locations_allowed', models.ManyToManyField(to='bac.Location')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='card_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bac.Cardholder'),
        ),
    ]
