# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0004_auto_20170212_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='mac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='relay',
            name='mac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='relay',
            name='paired_reader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bac.Reader'),
        ),
    ]
