# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0005_auto_20170213_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
