# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0003_relay_action'),
        ('users', '0002_auto_20170211_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bac.Reader'),
        ),
        migrations.AddField(
            model_name='user',
            name='relay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bac.Relay'),
        ),
    ]
